### PR TITLE
fix(rollup): fallback HTTP polling without filtering

### LINKED ISSUE #87: chore(rollup): support http polling without `eth_newBlockFilter` and `eth_getFilterChanges`
Some RPC providers don't support the filtering methods above. 

To support more free providers, we should add the possibility of polling by simply fetching new blocks and checking if the hash has changed. This is quite inefficient, but can be useful for testing / prototyping and if users don't have access to a websocket provider.

The code that calls `eth_getFilterChanges` is here in the `StandaloneContext` implementation:

https://github.com/paradigmxyz/op-rs/blob/9ccbc38efec724080f5e111474591586f4e86e2c/crates/rollup/src/driver/context/standalone.rs#L68

### PR DESCRIPTION
**Pull request by merklefruit**
Introduces a second method of polling via HTTP that doesn't rely on the `eth_filter` feature.
This will be auto-detected and triggered as fallback. It's mostly useful for test purposes.

- Fixes #87 

## Stack

- main
  - #88 
    - 👉 #89

### CODE REVIEW

File: crates/rollup/src/driver/context/standalone.rs [hunk 1]
```diff
@@ -65,28 +66,79 @@ impl StandaloneContext {
...
+            }),
+            Err(err) => {
+                if err
+                    .as_error_resp()
+                    .is_some_and(|resp| !resp.message.to_lowercase().contains("not supported"))
+                {
+                    // On any error other than "not supported", return the error and fail.
+                    error!("Failed to watch new blocks via HTTP");
+                    return Err(err);
+                }
```
Comment (refcell) [inline crates/rollup/src/driver/context/standalone.rs:101]: I think this is fine, but we should also then allow the user to pass an `--http` flag that uses http polling explicitly instead of subscriptions in order to not get caught in this block.

Comment (refcell) [inline crates/rollup/src/driver/context/standalone.rs:101]: I think this is fine, but we should also then allow the user to pass an `--http` flag that uses http polling explicitly instead of subscriptions in order to not get caught in this block.

**Review by refcell — APPROVED** [review]

File: crates/rollup/src/driver/context/standalone.rs (hunk 1 above)
Comment (merklefruit) [reply crates/rollup/src/driver/context/standalone.rs:101]: I don't fully get what the flag would mean, could you elaborate? 
If the URL scheme is HTTP we are forced to poll
